# This configuration does not include a processing node
# Which makes for faster setup times
version: '2.1'
volumes:
  Images:
  Annotations:
networks:
  web:
    external: true     
services:
  labelme:
    image: labelme
    container_name: labelme
    entrypoint: /bin/bash
    volumes:
      - ${WO_MEDIA_DIR}:/LabelMeAnnotationTool/Images
      - ${WO_ANNOTATIONS_DIR}:/LabelMeAnnotationTool/Annotations
    expose:
      - "80"
    tty: true
    stdin_open: true
    labels:
      - traefik.backend=labelme
      - traefik.frontend.rule=Host:labelme.${WO_HOST}
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.enable=true
    networks:
      - web  
